return function()
	local mark = require("harpoon.mark")
	local ui = require("harpoon.ui")

	vim.keymap.set("n", "<leader>aa", mark.add_file, { desc = "Add to Harpoon" })
	vim.keymap.set("n", "<leader>ae", ui.toggle_quick_menu, { desc = "Harpoon Toggle" })
	vim.keymap.set("n", "<C-j>", function()
		ui.nav_next()
	end)
	vim.keymap.set("n", "<C-k>", function()
		ui.nav_prev()
	end)
	--[[ vim.keymap.set("n", "<C-h>", function()
	ui.nav_file(1)
end)
vim.keymap.set("n", "<C-t>", function()
	ui.nav_file(2)
end)
vim.keymap.set("n", "<C-n>", function()
	ui.nav_file(3)
end)
vim.keymap.set("n", "<C-s>", function()
	ui.nav_file(4)
end) ]]
end
